# Spotify Popularity Prediction-ML Practice

In [1]:
# 기본적으로 사용할 파이썬 패키지
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# 1. 프로젝트 목표 및 목적

* 노래의 인기를 예측해보자!

# 2. 관련 데이터 수집

In [2]:
# 데이터 다운로드(song_data.csv / song_info.csv)
!gdown --id "1tFSeDdJYrOcVzQnxHQdJmV2Bp60rJ9O-"
!gdown --id "1NMpQ2nanbUUGOUo1PLBWgbxy59O69SZs"

Downloading...
From: https://drive.google.com/uc?id=1tFSeDdJYrOcVzQnxHQdJmV2Bp60rJ9O-
To: /content/song_data.csv
2.22MB [00:00, 70.7MB/s]
Downloading...
From: https://drive.google.com/uc?id=1NMpQ2nanbUUGOUo1PLBWgbxy59O69SZs
To: /content/song_info.csv
100% 1.24M/1.24M [00:00<00:00, 77.9MB/s]


In [3]:
# Pandas를 사용해서 CSV 파일 불러오기
# CSV 파일을 업로드 하세요
spotify_song_data= pd.read_csv("song_data.csv")
spotify_song_info= pd.read_csv("song_info.csv") 
song_info=spotify_song_info.copy()
song_data=spotify_song_data.copy()

In [4]:
song_info.head()

song_name  ...          playlist
0  Boulevard of Broken Dreams  ...  00s Rock Anthems
1                  In The End  ...  00s Rock Anthems
2           Seven Nation Army  ...  00s Rock Anthems
3                  By The Way  ...  00s Rock Anthems
4           How You Remind Me  ...  00s Rock Anthems

[5 rows x 4 columns]

In [5]:
song_data.head()

song_name  song_popularity  ...  time_signature  audio_valence
0  Boulevard of Broken Dreams               73  ...               4          0.474
1                  In The End               66  ...               4          0.370
2           Seven Nation Army               76  ...               4          0.324
3                  By The Way               74  ...               4          0.198
4           How You Remind Me               56  ...               4          0.574

[5 rows x 15 columns]

In [6]:
song_data.isnull().sum()

song_name           0
song_popularity     0
song_duration_ms    0
acousticness        0
danceability        0
energy              0
instrumentalness    0
key                 0
liveness            0
loudness            0
audio_mode          0
speechiness         0
tempo               0
time_signature      0
audio_valence       0
dtype: int64

In [7]:
song_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18835 entries, 0 to 18834
Data columns (total 15 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   song_name         18835 non-null  object 
 1   song_popularity   18835 non-null  int64  
 2   song_duration_ms  18835 non-null  int64  
 3   acousticness      18835 non-null  float64
 4   danceability      18835 non-null  float64
 5   energy            18835 non-null  float64
 6   instrumentalness  18835 non-null  float64
 7   key               18835 non-null  int64  
 8   liveness          18835 non-null  float64
 9   loudness          18835 non-null  float64
 10  audio_mode        18835 non-null  int64  
 11  speechiness       18835 non-null  float64
 12  tempo             18835 non-null  float64
 13  time_signature    18835 non-null  int64  
 14  audio_valence     18835 non-null  float64
dtypes: float64(9), int64(5), object(1)
memory usage: 2.2+ MB


# 3. 데이터 전처리

* 생략

In [8]:
song_data = pd.DataFrame(data = song_data)
song_data

song_name  ...  audio_valence
0      Boulevard of Broken Dreams  ...          0.474
1                      In The End  ...          0.370
2               Seven Nation Army  ...          0.324
3                      By The Way  ...          0.198
4               How You Remind Me  ...          0.574
...                           ...  ...            ...
18830              Let It Breathe  ...          0.300
18831                     Answers  ...          0.265
18832      Sudden Love (Acoustic)  ...          0.286
18833           Gentle on My Mind  ...          0.323
18834                    Up to Me  ...          0.581

[18835 rows x 15 columns]

# 4. 머신러닝을 위한 데이터 전처리

In [9]:
# train, test split
# 이러면 song_data 내부에 학습을 결정지을 요소로 song_popularity가 있는 것 아닌가?? -> 제거
from sklearn.model_selection import train_test_split
song_popularity = song_data['song_popularity']
song_data = song_data.drop('song_popularity', axis = 1)

In [10]:
song_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18835 entries, 0 to 18834
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   song_name         18835 non-null  object 
 1   song_duration_ms  18835 non-null  int64  
 2   acousticness      18835 non-null  float64
 3   danceability      18835 non-null  float64
 4   energy            18835 non-null  float64
 5   instrumentalness  18835 non-null  float64
 6   key               18835 non-null  int64  
 7   liveness          18835 non-null  float64
 8   loudness          18835 non-null  float64
 9   audio_mode        18835 non-null  int64  
 10  speechiness       18835 non-null  float64
 11  tempo             18835 non-null  float64
 12  time_signature    18835 non-null  int64  
 13  audio_valence     18835 non-null  float64
dtypes: float64(9), int64(4), object(1)
memory usage: 2.0+ MB


In [11]:
song_data.set_index('song_name', inplace=True)

In [12]:
X_train, X_test, y_train, y_test = train_test_split(song_data, song_popularity, random_state = 42)

In [13]:
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

(14126, 13) (4709, 13) (14126,) (4709,)


# 5. 학습

## 5.1 선형 모델

In [14]:
from sklearn.linear_model import LinearRegression
lin = LinearRegression()
lin.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

## 5.2 SVM

In [15]:
from sklearn.svm import SVR

In [16]:
model = SVR(kernel = 'rbf', gamma = 'scale')
model.fit(X_train, y_train)

SVR(C=1.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma='scale',
    kernel='rbf', max_iter=-1, shrinking=True, tol=0.001, verbose=False)

## 5.3 결정 트리

In [17]:
from sklearn.tree import DecisionTreeRegressor
from sklearn.tree import export_graphviz
from sklearn.model_selection import cross_val_score
import graphviz

model1 = DecisionTreeRegressor(max_depth = 10)
model1.fit(X_train, y_train)


DecisionTreeRegressor(ccp_alpha=0.0, criterion='mse', max_depth=10,
                      max_features=None, max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=1, min_samples_split=2,
                      min_weight_fraction_leaf=0.0, presort='deprecated',
                      random_state=None, splitter='best')

## 5.4 랜덤 포레스트

In [18]:
from sklearn.ensemble import RandomForestRegressor

In [19]:
model2 = RandomForestRegressor()
model2.fit(X_train, y_train)

RandomForestRegressor(bootstrap=True, ccp_alpha=0.0, criterion='mse',
                      max_depth=None, max_features='auto', max_leaf_nodes=None,
                      max_samples=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      n_estimators=100, n_jobs=None, oob_score=False,
                      random_state=None, verbose=0, warm_start=False)

# 6. 평가 및 튜닝
* 선형 모델, SVM, 결정 트리, 랜덤 포레스트의 평가 값을 확인

## 선형 모델

In [20]:
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error
from sklearn.model_selection import cross_val_score

In [21]:
song_predictions = lin.predict(X_test)
print(f"예측 결과 : {song_predictions}")


예측 결과 : [53.81239482 32.36141503 50.37454629 ... 52.47314228 59.82769611
 55.46805712]


In [22]:
linear_result = X_test[:] # 깊은 복사 필요
linear_result['song_predictions'] = song_predictions

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


In [23]:
linear_result # 끝에 각 곡에 맞는 예측 결과

song_duration_ms  ...  song_predictions
song_name                                 ...                  
Contrabando Y Traicion            212662  ...         53.812395
Nordlicht                         239730  ...         32.361415
I've Got A Woman                  171466  ...         50.374546
Crazy in Love                     227500  ...         54.567370
Don't Get Too High                209040  ...         63.880576
...                                  ...  ...               ...
Mr. Brightside                    222586  ...         53.153094
7/11                              213506  ...         56.708737
One Week                          169760  ...         52.473142
In My Feelings                    217925  ...         59.827696
Lover, Please Stay                247186  ...         55.468057

[4709 rows x 14 columns]

In [24]:
from sklearn.metrics import mean_squared_error

lin_mse = mean_squared_error(song_predictions, y_test)
lin_rmse = np.sqrt(lin_mse)
print(lin_rmse)

21.524735034541084


In [25]:
from sklearn.metrics import mean_absolute_error

lin_mae = mean_absolute_error(song_predictions, y_test)
print(lin_mae)

17.151322399667514


## SVM

In [26]:
print(f"학습 : {model.score(X_train, y_train)}")
print(f"예측 : {model.score(X_test, y_test)}")

학습 : -0.007538355685601461
예측 : -0.009837929618489172


## 결정 트리(Decision Tree)

In [27]:
cross_val_score(estimator = model1, X = song_data, y = song_popularity, cv = 5)

array([-0.1885189 , -0.05840264,  0.03992455,  0.0565358 ,  0.10819023])

In [58]:
dot_data = export_graphviz(decision_tree = model1,
                           feature_names = song_data.columns.values,
                           filled = True,
                           rounded = True)

graph = graphviz.Source(dot_data)
graph

## 랜덤 포레스트(Random Forest)

In [28]:
cross_val_score(estimator = model2, X = song_data, y = song_popularity, cv = 5)

array([0.14676896, 0.35838915, 0.35246036, 0.40187825, 0.45806569])

In [29]:
cross_val_score(estimator = model2, X = song_data, y = song_popularity, cv = 10)

array([0.12179416, 0.25555862, 0.35118497, 0.3885752 , 0.46349671,
       0.1748077 , 0.4390778 , 0.41686889, 0.42980926, 0.50146438])